#!/bin/sh

USER=`whoami`
HOST='rasa'
HOMEDIR='/home/'$NAME'/'
DOTS='/home/nick'

# snagging args
TEST=$1
LAST=''
for var in "$@"
do
    if [ -n "$LAST" ]; then
        if   [ "$LAST" = 'd' ]; then DOTS="$var"
        elif [ "$LAST" = 'h' ]; then HOST="$var"
        elif [ "$LAST" = 'p' ]; then HOMEDIR="$var"
        elif [ "$LAST" = 'u' ]; then USER="$var"
        fi
    else
        if [ $var -eq '--help' ]; then 
            echo 'Usage: init [option] ...
  options:
   --help                       display this message
   -d path,  --dots path        use as the dotfiles directory
   -p path,  --path path        use path as the home directory
   -u ident, --user ident       use ident as the identity
  examples:
   init
     home defaults to /home/`whoami`, name to `whoami`, and
     dots to $home/code/env/home
   init --dots /home/nick/code/dotfiles \
        --home /home/kcin \
        --user inkc
     strange setup, but whatever you want
'
        if [[ ${#var} -gt '2' ]] && [[ ${var:0:2} -eq '--' ]]; then
            LAST=${var:2:2}
        else LAST=${var:1}; fi
    fi
done
exit 0
echo 'need perms for this'
su
# which distro?
UNM=`uname -r`
if [[ $UNM = *ARCH ]]; then # arch specific:
    echo 'setting up for arch in three'
    sleep 1; echo 'two'; sleep 1; echo 'one'; sleep 1
    echo 'setting up locale'
    echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
    echo LANG=en_US.UTF-8 > /etc/locale.conf
    export LANG=en_US.UTF-8
    ln -s /usr/share/zoneinfo/US/Eastern /etc/localtime
    hwclock --systohc --utc
    echo $HOST > /etc/hostname
fi
exit 0


# symbolic links to dot files
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PRE=$DIR'/home/'
ePRE=$(readlink -f $PRE)
for f in `find $PRE -maxdepth 1 -mindepth 1`
do
  FILE=`basename $f`
  ln -Ts $PRE$FILE '/home/'$(whoami)'/'$FILE
done
